# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('CoordinatorId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('RegNo', models.CharField(max_length=10, unique=True)),
                ('PhoneNo', models.IntegerField()),
                ('MailId', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Event Name', max_length=20, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Venue', models.CharField(choices=[('s', 'New Sports Complex'), ('i', 'IEM Auditorium'), ('m', 'Mini Canteen'), ('c', 'CSE Department'), ('m', 'Mathematics Department')], default='s', max_length=15)),
                ('RegistrationFee', models.IntegerField(default=0)),
                ('Prize', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='EventCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.Coordinator')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Name of the Faculty', max_length=20)),
                ('PhoneNo', models.IntegerField()),
                ('MailId', models.EmailField(max_length=254)),
                ('RegNo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('ID', models.UUIDField(default=uuid.UUID('fe9ff637-35be-40db-ba8e-38fdc4074983'), primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=20)),
                ('PhoneNo', models.IntegerField()),
                ('College', models.CharField(blank=True, max_length=20, null=True)),
                ('MailId', models.EmailField(max_length=254)),
                ('RegNo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialGuest',
            fields=[
                ('GuestID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Name of the Guest', max_length=20)),
                ('PhoneNo', models.IntegerField(default=None)),
                ('MailId', models.EmailField(default=None, max_length=254)),
                ('Events', models.OneToOneField(blank=None, default=None, help_text='Hosted by', null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.Event')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.AddField(
            model_name='eventparticipates',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMS.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='Judge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.Faculty'),
        ),
        migrations.AddField(
            model_name='event',
            name='Winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.Participant'),
        ),
    ]
