# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('d72e0847-8d7a-4a37-b842-87e44e5ee231'), primary_key=True, serialize=False),
        ),
    ]
