# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0002_auto_20171020_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('01115e78-b7b0-46a2-8b1e-97cdae876e66'), primary_key=True, serialize=False),
        ),
    ]
