# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0003_auto_20171020_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('a6b129e8-11b6-45e2-8c5b-4a73a246bf30'), primary_key=True, serialize=False),
        ),
    ]
