# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0004_auto_20171020_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('491afd6e-49ea-4fb1-9860-a9e55c70f4f0'), primary_key=True, serialize=False),
        ),
    ]
