# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0005_auto_20171020_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='MailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='MailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='PhoneNo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('6d63c868-9e82-4078-9be8-f184196e9263'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='MailId',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='specialguest',
            name='MailId',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
