# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0006_auto_20171020_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('a2089719-b5ca-4ae4-bb23-5c919d265142'), primary_key=True, serialize=False),
        ),
    ]
