# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0007_auto_20171020_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('c4e017b6-abdf-4f37-b77f-b0d791e1b520'), primary_key=True, serialize=False),
        ),
    ]
