# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0008_auto_20171020_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('4bad8120-83ee-4093-acd6-0117884032c0'), primary_key=True, serialize=False),
        ),
    ]
