# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0009_auto_20171020_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('4ccd5047-2246-49eb-ae99-0aa0c87c4008'), primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='eventcoordinates',
            unique_together=set([('Event', 'Coordinator')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipates',
            unique_together=set([('Event', 'Participant')]),
        ),
    ]
