# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0011_auto_20171020_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialguest',
            name='Events',
        ),
        migrations.AddField(
            model_name='event',
            name='SpecialGuest',
            field=models.OneToOneField(blank=None, default=None, help_text='Hosted by', null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.SpecialGuest'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('72a1f4ef-6f9c-4fd5-b7e8-5b55ab5f7862'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
