# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0012_auto_20171021_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-DateTime']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Time',
        ),
        migrations.AddField(
            model_name='event',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 9, 49, 44, 986769)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('eb0c08bf-1054-486b-b7ca-88a4372829dd'), primary_key=True, serialize=False),
        ),
    ]
