# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0014_auto_20171021_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('1ca2a958-f8fc-42f2-8ca8-336c33fd0606'), primary_key=True, serialize=False),
        ),
    ]
