# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0015_auto_20171021_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-Date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('8fb50509-7c42-46c8-a1aa-d9b4f6e746a7'), primary_key=True, serialize=False),
        ),
    ]
