# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 07:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0016_auto_20171021_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='Password',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='Name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='SpecialGuest',
            field=models.OneToOneField(blank=None, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.SpecialGuest'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('848cc233-d06c-4728-8428-5ce21ef3068e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Password',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='specialguest',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
