# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0017_auto_20171022_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('f9377728-d830-470e-9855-49fee48f96dc'), primary_key=True, serialize=False),
        ),
    ]
