# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0018_auto_20171023_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SpecialGuest',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='EMS.SpecialGuest'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('b8cd2d6b-c8a5-4bd0-a96a-50c611aee064'), primary_key=True, serialize=False),
        ),
    ]
