# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0019_auto_20171023_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='SpecialGuest',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_guest', to='EMS.SpecialGuest'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('f5b77367-7e67-40d9-b9db-e1a232a0c19e'), primary_key=True, serialize=False),
        ),
    ]
