# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 08:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0020_auto_20171031_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('44e3da24-794f-4b33-a8a2-cdaeeaada527'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='PhoneNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^(\\+91)?d{9,10}$')]),
        ),
    ]
