# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 09:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0021_auto_20171109_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='PhoneNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='PhoneNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('394bce4d-95f8-41a8-aa70-6b77da5fc268'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='PhoneNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='specialguest',
            name='PhoneNo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
