# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:06
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EMS', '0024_auto_20171109_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('b2e9db0b-ecaf-4aa5-8a98-caba0bcfe3f0'), primary_key=True,
                                   serialize=False),
        ),
    ]
