# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:20
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EMS', '0025_auto_20171113_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
