# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:04
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EMS', '0027_auto_20171113_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='EMS.Faculty'),
        ),
        migrations.AlterField(
            model_name='event',
            name='SpecialGuest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='special_guest', to='EMS.SpecialGuest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='EMS.Participant'),
        ),
    ]
