# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 15:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('EMS', '0028_auto_20171114_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='Name',
            field=models.CharField(max_length=20, validators=[
                django.core.validators.RegexValidator(message='Invalid Name Entered', regex='[a-zA-Z\\s]*')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='Name',
            field=models.CharField(max_length=20, unique=True, validators=[
                django.core.validators.RegexValidator(message='Invalid Name Entered', regex='[a-zA-Z\\s]*')]),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Name',
            field=models.CharField(max_length=20, validators=[
                django.core.validators.RegexValidator(message='Invalid Name Entered', regex='[a-zA-Z\\s]*')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Name',
            field=models.CharField(max_length=20, validators=[
                django.core.validators.RegexValidator(message='Invalid Name Entered', regex='[a-zA-Z\\s]*')]),
        ),
        migrations.AlterField(
            model_name='specialguest',
            name='Name',
            field=models.CharField(max_length=20, validators=[
                django.core.validators.RegexValidator(message='Invalid Name Entered', regex='[a-zA-Z\\s]*')]),
        ),
    ]
